---
- name: Playbook with simplified date-time schedule handling
  hosts: localhost
  gather_facts: true
  vars:
    maint_schedules:
      # sample every day schedules
      - start: "0000-00-00 23:00:00"
        end:   "0000-00-00 07:00:00"
      - start: "0000-00-00 14:00:00"
        end:   "0000-00-00 16:00:00"
      # sample date-time from to different date-time
      - start: "2024-09-24 14:00:00"
        end:   "2024-09-31 18:00:00"
      # Sample holiday/vacation - 1 day or more
      - start: "2024-10-24 00:00:00"
        end:   "2024-10-24 23:59:59"

  tasks:
    - name: Fetch target system date time
      ansible.builtin.set_fact:
        system_datetime: "{{ ansible_date_time.date | replace('-', '') | replace(' ', '') | replace(':', '') }}{{ ansible_date_time.time | replace('-', '') | replace(' ', '') | replace(':', '')}}"
        in_maintenance: false

    - name: Check downtime schedules
      ansible.builtin.set_fact:
        in_maintenance: true
      when: schedule_datetime_start  < system_datetime  and schedule_datetime_end  > system_datetime
      vars:
        schedule_datetime_start: "{{ ansible_date_time.date | replace('-', '') | replace(' ', '') | replace(':', '') + maint_item.start[-8:] | replace('-', '') | replace(' ', '') | replace(':', '') if maint_item.start[0:10] == '0000-00-00' else maint_item.start | replace('-', '') | replace(' ', '') | replace(':', '') }}"
        schedule_datetime_end: "{{ ansible_date_time.date | replace('-', '') | replace(' ', '') | replace(':', '') + maint_item.end[-8:] | replace('-', '') | replace(' ', '') | replace(':', '')  if maint_item.end[0:10] == '0000-00-00' else maint_item.end | replace('-', '') | replace(' ', '') | replace(':', '') }}"
      loop: "{{ maint_schedules }}"
      loop_control:
        loop_var: maint_item
        label: "{{ maint_item.start }}-{{ maint_item.end }} ({{ schedule_datetime_start }}-{{schedule_datetime_end}})"

    - name: Skip if maintenance period
      ansible.builtin.debug:
        msg: "Skipping tasks due to maintenance window."
      when: in_maintenance | default(false)

    - name: Ru if not in maintenance period
      ansible.builtin.debug:
        msg: "This task will run outside maintenance window."
      when: not in_maintenance | default(false)
